apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deployment
  labels:
    app: healthcare
spec:
  selector:
    matchLabels:
      app: healthcare
  replicas: 2
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: capstone-app-container
          image: kalyanikolley/endtoendproject31july:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  selector:
    app: healthcare
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082
  type: NodePort # Change to LoadBalancer if needed
